sudo: false

language: rust

rust:
    - stable

matrix:
  allow_failures:

addons:
  apt:
    packages:
    - libportmidi-dev

script:
  - cargo build --verbose --release
  # This command generates a release.zip file.
  - make dist

deploy:
  provider: releases
  api_key:
    secure: "VYWJAUwO+K29dIq80rDtosICHzJ0bCsHHHcIoaiFxOEcR8jRKLsRGgGCmIdNP8+eDASlx18FC6/+ZRV0bA6ZrBd3+F7XvkOEGG1tYEdwkAWiAnWAy4ubc8o+uNYkacnDVvjyEGIv2eKmYoC7rHKlxjy0VKovB1YUeEMucrKHYN6Hrfmca4qJ9CU6WPSoVpx4ot0WVTV0U0xwr6tppepH2ZGd18J/7M3xQW/XFNZld7tQFCHE5JR7t2Sc/nPjYvI8fYDITseN7eyOHq4+bEv8ojuvYpDEGEML7z8BnN9ypT3N8n8DGinZUu4XNZ94zd12VqFJ5bUpvIxntYVuO0Dzt72CkZMeSRiw3a6PINEu8Zveqi64+ys67MALVXzpcoFE7XKEVL3CO36xJ37RT+eg2gBfW1reNMX5vyzyQRJE+FVzUXYD7CD0Do0VQbURroVNRichNezS58RtnRRvAlpdMNOZ0ArwgE7BjAZDfp9aCMHIHKiNg+N6FDcq8OW/FIKHJqPAwKDjZVNgqPEeQtFNz9OMRNtDjdb8+brq78WlP6mu7mHTLV5hQ9n9I68hnAMmnrcPIuFFMvxk4S4GA5APRM2q9BF78RwZOBz2+81fglWmd/2xTPy4MPGmKBPgXOYHO8jJNs7iSX0cj6X3W80g3HvfohsCfqCuB3SUNlcB4lA="
  file: 'release.zip'
  skip_cleanup: true
  on:
    tags
