[package]
name = "varjokuuntelija"
version = "0.1.0"
authors = ["Miranda Kastemaa <miranda@foldplop.com>"]

[lib]
name = "varjokuuntelu"
path = "src/lib.rs"

[[bin]]
name = "varjokuuntelija"
path = "src/main.rs"

[dependencies]
getopts = "0.2"
gl = "0.5"
notify = "2.5"
portmidi = "0.1"
time = "0.1"

[dependencies.glutin]
git = "https://github.com/ahihi/glutin"
